//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intern.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intern.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Application]
        ///SET IsDeleted = 1
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string DeleteApplication {
            get {
                return ResourceManager.GetString("DeleteApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	a.Id
        ///   ,s.Course
        ///   ,u.FirstName
        ///   ,u.LastName
        ///   ,u.Email
        ///   ,i.Title AS InternshipTitle
        ///   ,aps.[Name] AS ApplicationStatus
        ///   ,a.CreatedAt
        ///   ,a.UpdatedAt
        ///FROM [Application] a
        ///INNER JOIN Student s
        ///	ON a.FKStudenId = s.Id
        ///INNER JOIN [User] u
        ///	ON s.FKUserId = u.Id
        ///INNER JOIN Internship i
        ///	ON a.FKInternshipId = i.Id
        ///INNER JOIN ApplicationStatus aps
        ///	ON a.FKApplicationStatusId = aps.Id
        ///WHERE a.IsDeleted = 0
        ///ORDER BY a.Id DESC
        ///OFFSET @Offset ROWS
        ///FETCH NEXT @PageSize ROWS ONLY;.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from [Application] WHERE Id = @Id.
        /// </summary>
        public static string GetApplicationById {
            get {
                return ResourceManager.GetString("GetApplicationById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM [Application] WHERE IsDeleted = 0;.
        /// </summary>
        public static string GetTotalCount {
            get {
                return ResourceManager.GetString("GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [Application] (FKStudenId, FKInternshipId, FKApplicationStatusId)
        ///VALUES (@FKStudenId, @FKInternshipId, @FKApplicationStatusId).
        /// </summary>
        public static string InsertApplication {
            get {
                return ResourceManager.GetString("InsertApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [Application]
        ///SET FKInternshipId = @FKInternshipId,
        ///	FKApplicationStatusId = @FKApplicationStatusId,
        ///	UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string UpdateApplication {
            get {
                return ResourceManager.GetString("UpdateApplication", resourceCulture);
            }
        }
    }
}
