//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intern.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InternshipResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternshipResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intern.Resources.InternshipResource", typeof(InternshipResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Internship i
        ///WHERE i.IsDeleted = 0
        ///ORDER BY i.Id DESC
        ///OFFSET @Offset ROWS
        ///FETCH NEXT @PageSize ROWS ONLY;.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from Internship WHERE Id = @Id.
        /// </summary>
        public static string GetInternshipById {
            get {
                return ResourceManager.GetString("GetInternshipById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM Internship WHERE IsDeleted = 0;.
        /// </summary>
        public static string GetTotalCount {
            get {
                return ResourceManager.GetString("GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Internship (Title, [Description], [Location], StartDate, EndDate)
        ///VALUES (@Title, @Description, @Location, @StartDate, @EndDate).
        /// </summary>
        public static string InsertInternship {
            get {
                return ResourceManager.GetString("InsertInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Internship
        ///SET IsDeleted = 1
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string RemoveInternship {
            get {
                return ResourceManager.GetString("RemoveInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Internship
        ///SET Title = @Title
        ///   ,[Description] = @Description
        ///   ,[Location] = @Location
        ///   ,StartDate = @StartDate
        ///   ,EndDate = @EndDate
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string UpdateInternship {
            get {
                return ResourceManager.GetString("UpdateInternship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF (@Id &gt; 0)
        ///BEGIN
        ///UPDATE Internship
        ///SET Title = @Title
        ///   ,[Description] = @Description
        ///   ,[Location] = @Location
        ///   ,StartDate = @StartDate
        ///   ,EndDate = @EndDate
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id
        ///END
        ///ELSE
        ///BEGIN
        ///INSERT INTO Internship (Title, [Description], [Location], StartDate, EndDate)
        ///	VALUES (@Title, @Description, @Location, @StartDate, @EndDate)
        ///END.
        /// </summary>
        public static string UpsertInternship {
            get {
                return ResourceManager.GetString("UpsertInternship", resourceCulture);
            }
        }
    }
}
