//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intern.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intern.Resources.StudentResource", typeof(StudentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Student
        ///SET IsDeleted = 1
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string DeleteStudent {
            get {
                return ResourceManager.GetString("DeleteStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	s.*
        ///   ,u.FirstName
        ///   ,u.LastName
        ///   ,u.Email
        ///   ,u.Username
        ///   ,c.Name AS CollegeName
        ///FROM [Student] s
        ///INNER JOIN [User] u
        ///	ON s.FKUserId = u.Id
        ///INNER JOIN [College] c
        ///	ON s.FKCollegeId = c.Id
        ///WHERE s.IsDeleted = 0
        ///ORDER BY s.Id DESC
        ///OFFSET @Offset ROWS
        ///FETCH NEXT @PageSize ROWS ONLY;.
        /// </summary>
        public static string GetAll {
            get {
                return ResourceManager.GetString("GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Student WHERE Id = @Id.
        /// </summary>
        public static string GetStudentById {
            get {
                return ResourceManager.GetString("GetStudentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(1) FROM [Student] WHERE IsDeleted = 0;.
        /// </summary>
        public static string GetTotalCount {
            get {
                return ResourceManager.GetString("GetTotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Student (FKUserId, FKCollegeId, Course, YearOfStudy, ResumeBase64) VALUES (@FKUserId, @FKCollegeId, @Course, @YearOfStudy, @ResumeBase64).
        /// </summary>
        public static string InsertStudent {
            get {
                return ResourceManager.GetString("InsertStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Student
        ///SET Course = @Course
        ///   ,YearOfStudy = @YearOfStudy
        ///   ,ResumeBase64 = @ResumeBase64
        ///   ,UpdatedAt = @UpdatedAt
        ///WHERE Id = @Id.
        /// </summary>
        public static string UpdateStudent {
            get {
                return ResourceManager.GetString("UpdateStudent", resourceCulture);
            }
        }
    }
}
